ItemsSettings = {
    ["lawn_mover"] = {
        name = "Lawn Mover",
        capacity_cur = 50,
        capacity_max = 50,
        damage = 10,
    },
    ["coffee_token"] = {
        name = "Coffee Token",
        capacity_cur = 1,
        capacity_max = 1,
        damage = 0,
    },
    ["medi_probe"] = {
        name = "Medi-Probe",
        capacity_cur = 1,
        capacity_max = 1,
        damage = 1,
    },
    ["laser_pistol"] = {
        name = "Laser Pistol",
        accuracy = 40,
        capacity_cur = 6,
        capacity_max = 6,
        damage = 2,
    },
    ["laser_gun"] = {
        name = "Laser Gun",
        accuracy = 40,
        capacity_cur = 6,
        capacity_max = 6,
        damage = 2,
    },
    ["photon"] = {
        name = "Photon",
        accuracy = 6,
        capacity_cur = 18,
        capacity_max = 18,
        damage = 1,
    },
    ["laser_pack_1"] = {
        name = "Laser Pack-1",
        capacity_cur = 6,
        capacity_max = 6,
    },
    ["light_sabre"] = {
        name = "Light Sabre",
        accuracy = 100,
        capacity_cur = 0,
        capacity_max = 0,
        damage = 3,
    },
    ["blast_torch"] = {
        name = "Blast Torch",
        accuracy = 85,
        capacity_cur = 4,
        capacity_max = 4,
        damage = 5,
    },
}

UnitsSettings = {
    ["un_human"] = {
        faction = "",
        name = "Human",
        morale_cur = 255,
        morale_max = 255,
        stamina_cur = 190,
        stamina_max = 190,
        health_cur = 90,
        health_max = 90,
        armour = 12,
        action_points_cur = 20,
        action_points_max = 20,
        weapon_skill = 0,
    },
    ["un_combat_droid"] = {
        faction = "",
        name = "Combat Droid",
        morale_cur = 255,
        morale_max = 255,
        stamina_cur = 190,
        stamina_max = 190,
        health_cur = 90,
        health_max = 90,
        armour = 12,
        action_points_cur = 20,
        action_points_max = 20,
        weapon_skill = 0,
    },
    ["un_master_droid"] = {
        faction = "",
        name = "Master Droid",
        morale_cur = 255,
        morale_max = 255,
        stamina_cur = 190,
        stamina_max = 190,
        health_cur = 90,
        health_max = 90,
        armour = 12,
        action_points_cur = 20,
        action_points_max = 20,
        weapon_skill = 0,
    },
    ["un_android_medium"] = {
        faction = "",
        name = "Android",
        morale_cur = 255,
        morale_max = 255,
        stamina_cur = 190,
        stamina_max = 190,
        health_cur = 90,
        health_max = 90,
        armour = 12,
        action_points_cur = 20,
        action_points_max = 20,
        weapon_skill = 0,
    },
    ["un_android_light"] = {
        faction = "",
        name = "Android",
        morale_cur = 255,
        morale_max = 255,
        stamina_cur = 190,
        stamina_max = 190,
        health_cur = 90,
        health_max = 90,
        armour = 12,
        action_points_cur = 20,
        action_points_max = 20,
        weapon_skill = 0,
    },
    ["un_sentry_droid_heavy"] = {
        faction = "",
        name = "Sentry Droid",
        morale_cur = 255,
        morale_max = 255,
        stamina_cur = 190,
        stamina_max = 190,
        health_cur = 90,
        health_max = 90,
        armour = 12,
        action_points_cur = 20,
        action_points_max = 20,
        weapon_skill = 0,
    },
    ["un_sentry_droid_medium"] = {
        faction = "",
        name = "Sentry Droid",
        morale_cur = 255,
        morale_max = 255,
        stamina_cur = 190,
        stamina_max = 190,
        health_cur = 90,
        health_max = 90,
        armour = 12,
        action_points_cur = 20,
        action_points_max = 20,
        weapon_skill = 0,
    },
    ["un_sentry_droid_light"] = {
        faction = "",
        name = "Sentry Droid",
        morale_cur = 255,
        morale_max = 255,
        stamina_cur = 190,
        stamina_max = 190,
        health_cur = 90,
        health_max = 90,
        armour = 12,
        action_points_cur = 20,
        action_points_max = 20,
        weapon_skill = 0,
    },
    ["un_patrol_droid_medium"] = {
        faction = "",
        name = "Patrol Droid",
        morale_cur = 255,
        morale_max = 255,
        stamina_cur = 190,
        stamina_max = 190,
        health_cur = 90,
        health_max = 90,
        armour = 12,
        action_points_cur = 20,
        action_points_max = 20,
        weapon_skill = 0,
    },
    ["un_patrol_droid_light"] = {
        faction = "",
        name = "Patrol Droid",
        morale_cur = 255,
        morale_max = 255,
        stamina_cur = 190,
        stamina_max = 190,
        health_cur = 90,
        health_max = 90,
        armour = 12,
        action_points_cur = 20,
        action_points_max = 20,
        weapon_skill = 0,
    },
}

ObjectsSettings = {
}

TerrainSettings = {
}